### PR TITLE
Infinite while detection, variables, functions

### PR DESCRIPTION
**Pull request by alexisrdt**
### What does this pull request do?
- Checks for infinite while loops
- Adds variables, logic comparisons and arithmetic operators. Also shows an error when a variable is accessed before it was defined
- Adds support for functions with parameters and returns

### How was it tested?
Thoroughly.

### Notes
Limit functionality is broken when one option enables multiple blocks, but this is not a priority.

### CODE REVIEW

**Comment by alexisrdt** [comment]
[Create variables blocks](https://trello.com/c/VBeOGXNz/7-create-variables-blocks)

**Comment by alexisrdt** [comment]
[Create logical and arithmetical operators](https://trello.com/c/Mv8CioWl/8-create-logical-and-arithmetical-operators)

**Comment by alexisrdt** [comment]
[Add functions with parameters](https://trello.com/c/0mikYCTp/9-add-functions-with-parameters)

**Comment by alexisrdt** [comment]
[Detect infinite while loops](https://trello.com/c/SIfEq8jD/11-detect-infinite-while-loops)

**Review by enginbumbacher — APPROVED** [review]

**Pull request merged**
