### PR TITLE
Programmable world and MVP

### PR DESCRIPTION
**Pull request by alexisrdt**
### What does this pull request do?
- Adds a visualization of the stones Karel has collected
- Adds the possibility to program the world and the following blocks:
  - a "world main" block to program the behaviour of the world
  - an "end conditions" block to specify when the player should win and when they should lose
  - a "wait" block to wait for some number of steps to execute
  - a "spawn stone" block to place a stone at some location in the grid
  - a "random" block to get an random integer between two bounds
  - two getters to retrieve the number of stones Karel has and how many there are on the field

### How was it tested?
With a "Whac-A-Mole" MVP task.

### Notes
- Known bugs:
  - Switching to the "world" tab and switching back to the "Karel" one disables the scrollbar of the toolbox
  - Finishing the task while the world is executing a "wait" block makes the application hold indefinitely
- Missing features:
  - The world should have its own toolbox
  - The world code should not be editable when playing the task
  - There should be some UI feedback to know which tab is currently displayed
  - There should be an option to hide the "objective Karel" when events are enabled
  - There should be a check to make sure the end conditions at least have a "success" block
  - Unchecking the "events" should bring back to the "Karel" tab

### CODE REVIEW

**Comment by alexisrdt** [comment]
[Whac-a-mole (MVP)](https://trello.com/c/ura6FZMC/17-whac-a-mole-mvp)

**Comment by alexisrdt** [comment]
[Programmable world](https://trello.com/c/LvPPMfy1/19-programmable-world)

**Comment by alexisrdt** [comment]
[Backpack visualization](https://trello.com/c/xP9ahrww/18-backpack-visualization)

**Review by enginbumbacher — COMMENTED** [review]
There are two problems that I have encountered.

The first one is with the variable: There is only one variable I can define, and then I can rename it. But I can't have two different variables. See images. 
Screenshot 2023-12-22 at 17 54 46
Screenshot 2023-12-22 at 17 54 51

The second problem: The end condition does not get triggered even when it should. See image. 
Screenshot 2023-12-22 at 17 57 24

**Comment by alexisrdt** [comment]
For the variable, it's the Blockly default behaviour, I didn't search how to allow the user to create more variables. There is however a trick to do so: create a function, add a parameter with the name you want, it will then appear in the list of variables (and you can remove the function if you don't need it).

For the fail condition, I think you just got the "Karel stone count" and "world stone count" mixed up. Here, you used the Karel stone count, and Karel indeed has 0 blue stones. If you use the world stone count, it should trigger the fail condition.

**Comment by enginbumbacher** [comment]
Ah I see. Re: Variable, I'll have to fix this later then, that's for sure. 
Re: fail condition - yes I see, I didn't even read the blocks properly then. With the world stone, this works. That's great the.

**Pull request merged**
